<?php
# settings.php

define("ALLOWED_HTTP_ORIGINS", $_ENV["ALLOWED_HTTP_ORIGINS"] ?? []);
define("HTTP_ORIGIN_FALLBACK_ON_FAILURE", ALLOWED_HTTP_ORIGINS[0] ?? []);

const SHOW_PHP_ERRORS = false;
const RESPOND_JSON_PRETTY_PRINTING = false;

const REGISTER_DEFAULT_AVATAR = "/" . BASE_URL . "/assets/logo-192.webp?t=4096";
const REGISTER_USERNAME_MIN_CHARS = 3;
const REGISTER_USERNAME_MAX_CHARS = 20;
const REGISTER_PASSWORD_MIN_CHARS = 6;
const REGISTER_PASSWORD_MAX_CHARS = 32;

const NEWPOST_MIN_TITLE_LENGTH = 3;
const NEWPOST_MAX_TITLE_LENGTH = 96;
const NEWPOST_MAX_DESC_LENGTH = 2048;
const NEWPOST_ENABLE_STRICT_MIME_CHECKING = false;
const NEWPOST_MAX_FILE_SIZE = 20 * 1048576;
const NEWPOST_IMAGE_WEBP_COMPRESS_QUALITY = 60;

const CMT_MIN_LENGTH = 1;
const CMT_MAX_LENGTH = 2048;

const BIO_MAX_LENGTH = 1024;

const AVATAR_IMAGE_MAX_FILE_SIZE = 6 * 1048576;
const AVATAR_IMAGE_MAX_WIDTH = 5000;
const AVATAR_IMAGE_MAX_HEIGHT = 5000;
const AVATAR_IMAGE_WEBP_COMPRESS_QUALITY = 45;

const SESSION_CREATION_EXPIRY = 86400 * 14;
const SESSION_EXPIRY_BEFORE_ROTATION = 86400 * 2;
